################################################################################

- date: January 7, 2024 ## Service was cancelled due to weather
  title: First Sunday after the Epiphany
  mp3: false
  bulletin: false
- date: January 14, 2024
  title: Second Sunday after the Epiphany
  mp3: true
  bulletin: false
- date: January 21, 2024
  title: Third Sunday after the Epiphany
  mp3: true
  bulletin: false
- date: January 28, 2024
  title: Fourth Sunday after the Epiphany
  mp3: true
  bulletin: false

################################################################################

- date: Febryary 4, 2024
  title: Fifth Sunday after the Epiphany
  mp3: true
  bulletin: false
- date: Febryary 11, 2024
  title: Last Sunday after the Epiphany
  mp3: false
  bulletin: false
- date: Febryary 18, 2024
  title: First Sunday in Lent
  mp3: true
  bulletin: false
- date: Febryary 25, 2024
  title: Second Sunday in Lent
  mp3: true
  bulletin: false

################################################################################

- date: March 3, 2024
  title: Third Sunday in Lent
  mp3: true
  bulletin: false
- date: March 10, 2024
  title: Fourth Sunday in Lent
  mp3: true
  bulletin: false
- date: March 17, 2024
  title: Fifth Sunday in Lent
  mp3: false
  bulletin: false
- date: March 24, 2024
  title: "Sunday of the Passion: Palm Sunday"
  mp3: true
  bulletin: false
- date: March 31, 2024
  title: "Easter Day"
  mp3: true
  bulletin: false

################################################################################

- date: April 7, 2024
  title: Second Sunday of Easter
  mp3: true
  bulletin: false
- date: April 14, 2024
  title: Third Sunday of Easter
  mp3: true
  bulletin: false
- date: April 21, 2024
  title: Fourth Sunday of Easter
  mp3: true
  bulletin: false
- date: April 28, 2024
  title: Fifth Sunday of Easter
  mp3: true
  bulletin: false

################################################################################

- date: May 5, 2024
  title: Sixth Sunday of Easter
  mp3: true
  bulletin: false
- date: May 12, 2024
  title: Seventh Sunday of Easter
  mp3: true
  bulletin: false
- date: May 19, 2024
  title: Day of Pentecost
  mp3: false
  bulletin: false
- date: May 26, 2024
  title: First Sunday after Pentecost
  mp3: true
  bulletin: false

################################################################################

- date: June 2, 2024
  title: Second Sunday after Pentecost
  mp3: true
  bulletin: false
- date: June 9, 2024
  title: Third Sunday after Pentecost
  mp3: true
  bulletin: false
- date: June 16, 2024
  title: Fourth Sunday after Pentecost
  mp3: true
  bulletin: false
- date: June 23, 2024
  title: Fifth Sunday after Pentecost
  mp3: true
  bulletin: false
- date: June 30, 2024
  title: Sixth Sunday after Pentecost
  mp3: false
  bulletin: false

################################################################################

- date: July 7, 2024
  title: Seventh Sunday after Pentecost
  mp3: true
  bulletin: false
- date: July 14, 2024
  title: Eighth Sunday after Pentecost
  mp3: true
  bulletin: false
- date: July 21, 2024
  title: Ninth Sunday after Pentecost
  mp3: true
  bulletin: false
- date: July 28, 2024
  title: Tenth Sunday after Pentecost
  mp3: false
  bulletin: false

################################################################################

- date: August 4, 2024
  title: Eleventh Sunday after Pentecost
  mp3: true
  bulletin: false