################################################################################

- date: January 7, 2024 ## Service was cancelled due to weather
  title: First Sunday after the Epiphany
  mp3: false
  bulletin: false
- date: January 14, 2024
  title: Second Sunday after the Epiphany
  mp3: true
  bulletin: false
- date: January 21, 2024
  title: Third Sunday after the Epiphany
  mp3: true
  bulletin: false
- date: January 28, 2024
  title: Fourth Sunday after the Epiphany
  mp3: true
  bulletin: false

################################################################################

- date: Febryary 4, 2024
  title: Fifth Sunday after the Epiphany
  mp3: true
  bulletin: false
- date: Febryary 11, 2024
  title: Last Sunday after the Epiphany
  mp3: false
  bulletin: false
- date: Febryary 18, 2024
  title: First Sunday in Lent
  mp3: true
  bulletin: false