- date: 01/05/2020
  title: "Second Sunday after Christmas"
  summary: "ALord, may each of us recognize and follow your will for us during the New Year."
  sermon: "We Beheld His Glory, Hallelujah!"
  pdf: 2020/bulletin/2020-01-05-WRC-bulletin.pdf
  #mp3: 2020/audio/2020-01-05-WRC-service.mp3
  type: service

- date: 02/09/2020
  title: "February 9, 2020"
  summary: "February 9, 2020"
  #sermon: "We Beheld His Glory, Hallelujah!"
  #pdf: 2020/bulletin/2020-01-05-WRC-bulletin.pdf
  mp3: 2020/audio/2020-02-09-WRC-service.mp3
  type: service
  latest: true

- date: 02/23/2020
  title: "February 23, 2020"
  summary: "February 23, 2020"
  #sermon: "We Beheld His Glory, Hallelujah!"
  #pdf: 2020/bulletin/2020-01-05-WRC-bulletin.pdf
  mp3: 2020/audio/2020-02-23-WRC-service.mp3
  type: service
  latest: true

- date: 03/01/2020
  title: "March 1, 2020"
  summary: "March 1, 2020"
  #sermon: "We Beheld His Glory, Hallelujah!"
  #pdf: 2020/bulletin/2020-01-05-WRC-bulletin.pdf
  mp3: 2020/audio/2020-03-01-WRC-service.mp3
  type: service
  latest: true