################################################################################

- date: January 8, 2023
  title: First Sunday after the Epiphany
  mp3: true
  bulletin: false
- date: January 15, 2023
  title: Second Sunday after the Epiphany
  mp3: true
  bulletin: false
- date: January 22, 2023
  title: Third Sunday after the Epiphany
  mp3: true
  bulletin: false
- date: January 29, 2023
  title: Fourth Sunday after the Epiphany
  mp3: true
  bulletin: false

################################################################################

- date: February 5, 2023
  title: Fifth Sunday after the Epiphany
  mp3: true
  bulletin: false
- date: February 12, 2023
  title: Sixth Sunday after the Epiphany
  mp3: true
  bulletin: false
- date: February 19, 2023
  title: Last Sunday after Epiphany
  mp3: true
  bulletin: false
- date: February 26, 2023
  title: First Sunday in Lent
  mp3: true
  bulletin: false
  
################################################################################

- date: March 5, 2023
  title: Second Sunday in Lent
  mp3: true
  bulletin: false
- date: March 12, 2023
  title: Third Sunday in Lent
  mp3: true
  bulletin: false
- date: March 19, 2023
  title: Fourth Sunday in Lent
  mp3: true
  bulletin: false
- date: March 26, 2023
  title: Fifth Sunday in Lent
  mp3: true
  bulletin: false

################################################################################

- date: April 2, 2023
  title: "Sunday of the Passion: Palm Sunday"
  mp3: true
  bulletin: false
- date: April 9, 2023
  title: "Easter Sunday"
  mp3: false
  bulletin: false
- date: April 16, 2023
  title: "Second Sunday of Easter"
  mp3: true
  bulletin: false
- date: April 23, 2023
  title: "Third Sunday of Easter"
  mp3: true
  bulletin: false
- date: April 30, 2023
  title: "Fourth Sunday of Easter"
  mp3: true
  bulletin: false

################################################################################

- date: May 7, 2023
  title: "Fifth Sunday of Easter"
  mp3: true
  bulletin: false
- date: May 14, 2023
  title: "Sixth Sunday of Easter"
  mp3: true
  bulletin: false
  
