################################################################################

- date: January 8, 2023
  title: First Sunday after the Epiphany
  mp3: true
  bulletin: false
- date: January 15, 2023
  title: Second Sunday after the Epiphany
  mp3: true
  bulletin: false
- date: January 22, 2023
  title: Third Sunday after the Epiphany
  mp3: true
  bulletin: false
- date: January 29, 2023
  title: Fourth Sunday after the Epiphany
  mp3: true
  bulletin: false

################################################################################

- date: February 5, 2023
  title: Fifth Sunday after the Epiphany
  mp3: true
  bulletin: false
  
